.TH ySTR_max 3 2015-jun "linux" "interfacing applications with library"

.SH NAME
.B ySTR
\- library of secure, useful, second-order string functions

.SH PATRON
.B astrea-kori
(star-maiden)
virgin goddess of justice, purity, and precision

.SH IMAGERY
elegant woman with shinning wings, angel light, and flamming torch

.SH SUMMARY
ySTR is a second-order string handling library, supplementing the c-string
standard, with widely-used, standardized, well-tested, and traceable string
functions.  DRY (don't repeat yourself), standardize, centralize.

.SH DOCUMENTATION FILES
.nf
ySTR (3)           interfacing applications with library
ySTR_chars (3)     specifics of character functions
ySTR_exec (3)      specifics of program execution functions
ySTR_extend (3)    specifics of extended shrike charset (128-255)
ySTR_max (3)·······specifics of length limited functions
ySTR_nums (3)      specifics of number format conversions
ySTR_solo (3)      specifics of helpful string macros/constants
ySTR (7)           decision rationale, scope, and objectives

.SH TABLE OF CONTENTS
.nf  
a) overview        quick summary

.SH A) OVERVIEW
