.TH ySTR 3 2015-jun "linux" "heatherly custom tools manual"

.SH NAME
ySTR \- library of secure and useful string handling functions
.SH SYNOPSIS
.nf
.B #include  <ySTR.h>
.sp
.R  ---(strings)-----------------------------------
.BI "char strlcpy   (char *" "a_dst" ", char *" "a_src" ", int " "a_max" ");"
.BI "char strlcat   (char *" "a_dst" ", char *" "a_src" ", int " "a_max" ");"
.BI "int  strllen   (char *" "a_src" ", int " "a_max" ");"
.BI "char strltrunc (char *" "a_src" ", int " "a_max" " );"
.BI "int  strltrim  (char *" "a_src" ", char " "a_mode" ", int " "a_max" ");"
.BI "int  strltrepl (char *" "a_src" ", char *" "a_old" ", char *" "a_new" ", int " "a_cnt" ", int " "a_max" ");"
.BI "int  strltclean(char *" "a_src" ", char " "a_mode" ", char " "a_comp" ", int " "a_cnt" ", int " "a_max" ");"

.sp
.R  ---(delimiters)--------------------------------
.BI "int  strldcnt  (char *" "a_src" ", char " "a_del" ", int " "a_max" ");"
.BI "int  strldpos  (char *" "a_src" ", char " "a_del" ", int " "a_cnt" ", int " "a_max" ");"
.BI "int  strldchg  (char *" "a_src" ", char " "a_del" ", char " "a_new" ", int " "a_max" ");"
.BI "int  strldchg  (char *" "a_src" ", char " "a_del" ", int " "a_max" ");"
.sp
.R  ---(args)--------------------------------------
.BI "char strlargs  (char *" "a_src" ", int " "a_cnt" ", int *" "a_argc" ", char **" "a_argv" ", int " "a_max" ");"
.sp
.R  ---(conversion)--------------------------------
.BI "char strl2bin    (char *" "a_src" ", double *" "a_val" ", int " "a_max" ");"
.BI "char strl2oct    (char *" "a_src" ", double *" "a_val" ", int " "a_max" ");"
.BI "char strl2hex    (char *" "a_src" ", double *" "a_val" ", int " "a_max" ");"
.BI "char strl2real   (char *" "a_src" ", double *" "a_val" ", int " "a_max" ");"
.sp
.R  ---(formatting)--------------------------------
.BI "char strl4bin   (double " "a_val" ", char *" "a_src" ", int " "a_cnt" ", char " "a_frm" ", int " "a_max" ");"
.BI "char strl4oct   (double " "a_val" ", char *" "a_src" ", int " "a_cnt" ", char " "a_frm" ", int " "a_max" ");"
.BI "char strl4hex   (double " "a_val" ", char *" "a_src" ", int " "a_cnt" ", char " "a_frm" ", int " "a_max" ");"
.BI "char strl4comma (double " "a_val" ", char *" "a_src" ", int " "a_cnt" ", char " "a_frm" ", int " "a_max" ");"
.sp
.R  ---(logging/unit testing)----------------------
.BI "char* ySTR_version   (void);"
.BI "char  ySTR_debug     (char " "a_flag" ");"
.BI "char  ySTR_testloud  (void);"
.BI "char  ySTR_testquiet (void);"
.sp
.B link with -L/usr/local/libs -lySTR or -lySTR_debug



